### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by adruet** [TykTechnologies/tyk-sync#48] opened 2020-08-25 15:12 UTC
Hello,

When I try to install I have this issue :

# github.com/TykTechnologies/tyk-sync/tyk-swagger
/root/Projects/Proj1/src/github.com/TykTechnologies/tyk-sync/tyk-swagger/swagger.go:155:23: multiple-value uuid.NewV4() in single-value context
# github.com/TykTechnologies/tyk-sync/clients/dashboard
/root/Projects/Proj1/src/github.com/TykTechnologies/tyk-sync/clients/dashboard/apis.go:361:48: multiple-value uuid.NewV4() in single-value context
/root/Projects/Proj1/src/github.com/TykTechnologies/tyk-sync/clients/dashboard/policies.go:271:52: multiple-value uuid.NewV4() in single-value context
# github.com/TykTechnologies/tyk-sync/clients/gateway
/root/Projects/Proj1/src/github.com/TykTechnologies/tyk-sync/clients/gateway/client.go:296:48: multiple-value uuid.NewV4() in single-value context

OS Version :

 - Debian 8.11

Go Version : 

- go version go1.13.3 linux/amd64

Go Env 

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/Projects/Proj1"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build407833154=/tmp/go-build -gno-record-gcc-switches"

Thanks you

**Comment by adruet** [comment] 2020-08-31 07:06
Hello,

@alexdjpre 
By settings the variable GO111MODULE="on" it's working for me.

Regards

**Comment by l3ender** [comment] 2020-12-14 16:05
This seems like a duplicate of https://github.com/TykTechnologies/tyk-sync/issues/48.

**Comment by komalsukhani** [comment] 2024-07-12 08:18
Closing as it's duplicate of #41

**Closed by komalsukhani** 2024-07-12 08:18 UTC
Labels: docs
